### ISSUE TITLE
Request for updates.

### ISSUE THREAD

**Issue by Ceruleansand71** [cardcraft/EdgeNext#1]
I want more updatesssss :(((((

**Comment by cardcraft** [comment]
They're on their way, trust me. I'm working on an auto assignment option but it's harder without detection, any ideas?

**Comment by cardcraft** [comment]
You do gotta remember this is a one man band

**Comment by Ceruleansand71** [comment]
true

**Comment by cardcraft** [comment]
Hey man, You got any ideas? I'm open for taking

**Comment by Ceruleansand71** [comment]
you could maybe add an auto-guesser

**Comment by cardcraft** [comment]
I'm working on an option to make the little inside window bigger, will work on more things as time goes on.
